### ISSUE TITLE
Deserializing a LinkedCRS always errors with "must be a dereferenceable URI"

### ISSUE THREAD

**Issue by JoeRobich** [GeoJSON-Net/GeoJSON.Net#101]
Since the `CrsConverter` instantiates the LinkedCRS with `string.Empty` as the href, it always fails the href length guard.

**Comment by matt-lethargic** [comment]
Hey @JoeRobich saw your PR, is there any chance you could add in a test for this for regression purposes?

**Comment by JoeRobich** [comment]
Thanks for looking things over. I pushed a regression test to #102.
