### ISSUE TITLE
Removing older DotNet Frameworks in 2.0.0 branch?

### ISSUE THREAD

**Issue by TimF2004** [GeoJSON-Net/GeoJSON.Net#103]
For the 2.0.0 branch, is there any need to keep the 3.5 and 4.0 frameworks? 

Also, NetCore1.1 and NetCore2.0 could be added.

Thoughts?

**Comment by matt-lethargic** [comment]
Is there a reason to remove 3.5 and 4.0? This library is built around Newtonsoft's Json.Net which still supports all the way back to .Net 2.0 so really we should be supporting that as well! 

The library is already built in .Net Standard 1.0 and 1.1 so this covers .Net Core 1.1. I can add .Net Standard 2.0

**Comment by TimF2004** [comment]
No reason other than getting away from maintaining code written against a 10/7 year old frameworks that are not being supported. 

Plus, I didn't want to download and install them on my laptop. :)

**Comment by TimF2004** [comment]
Fine by me.
