### ISSUE TITLE
[Question] Position Constructor long\lat validation

### ISSUE THREAD

**Issue by DizzyDeveloper** [GeoJSON-Net/GeoJSON.Net#106]
Why does one Position constructor validate the provided long, lat and alt validate the parameters but not the other. 
I understand for the constructor taking strings that you validate the that the provided parameters are doubles but why then check the lat/long parameters are outside the expected range in one but not the other?

Is it possible to have this validation check in both constructors?

**Comment by chgennar** [comment]
This has been added

**Comment by DizzyDeveloper** [comment]
@chgennar Ah excellent! Thank you.
