### ISSUE TITLE
Lat Long validation in ctor 

### ISSUE THREAD

**Issue by matt-lethargic** [GeoJSON-Net/GeoJSON.Net#111]
The validation in the ctor of Position only works with lat/long, WGS84 can have many CRS'

See discussion on https://github.com/GeoJSON-Net/GeoJSON.Net/pull/108

**Comment by steveoh** [comment]
Did this get pushed as 1.1.70 to nuget? The versions aren't aligned between gh and nuget... what's up?

**Comment by steveoh** [comment]
📞?

**Comment by xfischer** [comment]
Hi @steveoh. I'm trying to ping @matt-lethargic on this.

**Comment by matt-lethargic** [comment]
On it now, just catching up where everything was left off a while back.

**Comment by steveoh** [comment]
📞?

**Comment by xfischer** [comment]
Hi @steveoh ! Had a chat with @matt-lethargic. He's not available at the moment.
I'll handle this and release the package ASAP.

**Comment by xfischer** [comment]
Published version 1.1.71

**Comment by steveoh** [comment]
seems like a partial peel back... https://github.com/GeoJSON-Net/GeoJSON.Net/blob/master/src/GeoJSON.Net/Geometry/Position.cs#L59-L67

**Comment by xfischer** [comment]
I would call it unvoluntary-preemptive-deceptional-teasing... Buuuut I'll get that fixed today.

**Comment by xfischer** [comment]
Package 1.1.72 released. Please close when deception is far gone ;)

**Comment by xfischer** [comment]
@steveoh Is this resolved with 1.1.72 ?

**Comment by steveoh** [comment]
Code looks better 👍
