### ISSUE TITLE
GeoJSON-Net does not work with Newtonsoft.Json v11

### ISSUE THREAD

**Issue by GuidedByCthulhu** [GeoJSON-Net/GeoJSON.Net#113]
Looks like it's explicitly looking for a version of Newtonsoft.Json where the Major Version is equal to 10.  If you attempt to serialize the GEOJson-Net objects using Newtonsoft.Json v11, an exception gets thrown as the assembly doesn't get loaded.    

Same code will work fine if you downgrade to v10.

**Comment by matt-lethargic** [comment]
Which exception gets thrown?

**Comment by matt-lethargic** [comment]
Have you tried an assembly redirect in your web.config for Newtonsoft.json? something like:

    <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
            <dependentAssembly>
                <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
                <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
            </dependentAssembly>
    ....

**Comment by GuidedByCthulhu** [comment]
Nope, I have not.  I'll try it later today, and report back on success/failure.

**Comment by matt-lethargic** [comment]
Did you have any luck?

**Comment by GuidedByCthulhu** [comment]
I wish to apologize; this had fallen off my radar / I forgot to report back.
Binding redirection solved the issue.
