### ISSUE TITLE
Feature.Equals throws an error if Geometry is null

### ISSUE THREAD

**Issue by MattFenner** [GeoJSON-Net/GeoJSON.Net#115]
If feature1 has a null geometry, then feature1.Equals(feature2) will throw an exception.

somewhat related to https://github.com/GeoJSON-Net/GeoJSON.Net/issues/80

**Comment by matt-lethargic** [comment]
I've committed a fix for this an will push out in the next release

**Comment by darbio** [comment]
Is this fixed? I get the same issue with 1.1.70

**Comment by xfischer** [comment]
Should be fixed with 1.1.71 released a few minutes ago. Let me know @darbio and @MattFenner.

**Comment by darbio** [comment]
I'll test and let you know if it doesn't work for my use case

**Comment by matt-lethargic** [comment]
Closing, happy to reopen if issue.
