### ISSUE TITLE
Feature constructor requires concrete implementation of Dictionary

### ISSUE THREAD

**Issue by justinhachemeister** [GeoJSON-Net/GeoJSON.Net#116]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem with the latest version.
    * Attempted to debug the issue.
    * Checked the documentation to see if a solution already exists.
    * Checked that your issue is not already filed.

### Description

`Feature(IGeometryObject, Dictionary<string, object>, string)` does not accept subclasses of `IDictionary<string, object>`.

I have an application where I have a domain model that is the Feature Properties dictionary. This class inherits `IDictionary<string, object>` for testability - which causes the code to use the `Feature(IGeometryObject, object, string)` constructor. The only way to use the `Feature` class in my desired way is to map to a new `Dictionary<string, object>`.

This can be corrected by following the [Liskov Substitution Principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle):

> Substitutability is a principle in object-oriented programming stating that, in a computer program, if S is a subtype of T, then objects of type T may be replaced with objects of type S (i.e. an object of type T may be substituted with any object of a subtype S) without altering any of the desirable properties of the program (correctness, task performed, etc.).

### Steps to Reproduce

1. Provide `IDictionary<string, object>` to `Feature(IGeometryObject, Dictionary<string, object>, string)`
2. Compile and Run.
3. Runtime Exception stating:

> Parameter count mismatch.

**Expected behavior:** [What you expect to happen]

Constructor should be accept substitutions of `IDictionary<string, object>` allowing:

1. Dependency Injection
1. Test Doubles/Mocking
1. Flexibility

**Actual behavior:** [What actually happens]

Ambiguous Runtime Exception occurs stating `Parameter count mismatch`.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

You can get this information from the library being used that is causing the issue. Also, please include the OS and what version of the OS you're running.

*Version Information:*  `1.1.64`
*Operating System:* Windows 10

### Additional Information

> Any additional information, configuration or data that might be necessary to reproduce or resolve the issue.

I will be submitting a pull request with the updated constructors and unit tests verifying the behavior as soon as I have the issue number to tag it with.

I am submitting a pull request, but wanted an issue to tag it with.

**Comment by matt-lethargic** [comment]
Hi just to let you know I'm going to be looking at this over the next few days. Sorry for the delay
