### ISSUE TITLE
Support geojson-ld

### ISSUE THREAD

**Issue by irv** [GeoJSON-Net/GeoJSON.Net#120]
http://geojson.org/geojson-ld/

**Comment by xfischer** [comment]
Hi @irv ! Thanks for reporting your wishes. 

(A ***sentence***, prefixed by a short presentation (**Hi!** is accepted, even **Yo!**) would add some smoothness).

I don't know JSON-LD, so can you elaborate about JSON-LD, what it means for GeoJSON and how you would use it ?

The aim here is to know if this is a core feature of GeoJSON.Net or more like an additional layer, which should then be addressed in the [Contrib repo](https://github.com/GeoJSON-Net/GeoJSON.Net.Contrib).

**Comment by irv** [comment]
I'm sorry, I submitted before I'd meant to (it's Friday!)

JSON-LD is described in detail in the spec: https://www.w3.org/TR/json-ld/ but as a summary, it's a method of providing a schema for a document (the `@context`)

I would like to use GeoJSON.Net in one of my projects and have the output serialised to jsonld (or specifically, geojson-ld, which is described (briefly) on the geojson site), so that I can correctly dereference it from other linked data contexts.

However, i would like to draw your attention to this note:
> Nested GeoJSON coordinate arrays are incompatible with the processing model of JSON-LD 1.0. 

and also note that any identifiers (such as `feature`'s `id`)should be IRIs

**Comment by xfischer** [comment]
Thanks @irv for those details.
So (correct if wrong) you'll need a thin layer between JSON-LD and GeoJSON.Net to perform conversions from/to GeoJSON.Net from/to GeoJson-LD
I'll transfer this to the contrib repo (let's imagine a NuGet named GeoJSON.Net.Contrib.Json-LD)
Seems that [json-ld.net](https://github.com/linked-data-dotnet/json-ld.net) could be helpful.

Do you, as a developer, could be involved in this dev ?

**Comment by xfischer** [comment]
Hi @irv ! 
What are your thoughts ?

**Comment by xfischer** [comment]
Wooot ! This issue has reached the maximum allowed silence length threshold. Closing. Please reopen if necessary.
