### ISSUE TITLE
Not used JsonPropertyAttibute from overrided property "Type" in class "Feature"

### ISSUE THREAD

**Issue by gansmmm** [GeoJSON-Net/GeoJSON.Net#121]
In

**Comment by xfischer** [comment]
Hi @gansmmm ! Thanks for reporting. 
I think I'm also In.
Can you elaborate a little bit more ?

**Comment by gansmmm** [comment]
Sorry, the problem was in my environment.
The problem was that during serialization, instead of "type", it returned "Type".
Thanks for the quick response.
