### ISSUE TITLE
Assemblies are not Strongly Named, hence unusable to me in current form

### ISSUE THREAD

**Issue by peSHIr** [GeoJSON-Net/GeoJSON.Net#123]
I tried to reference your NuGet package, but unfortunately (as my C# solution consists of Strongly Named assemblies), all I get at runtime isthe following exception:

System.IO.FileLoadException: 'Could not load file or assembly '[name], Version=#.#.#.#, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

Could you please update your package to be strongly named? Or else I see no other option to include some of your source code in my own instead of referencing your NuGet package, which sort of defeats the whole purpose, doesn't it...?

**Comment by matt-lethargic** [comment]
Hi @peSHIr in all honesty I've never created a Strongly Named assembly, let me do some reading and I'll back to you.

@xfischer what are your thoughts on this?

**Comment by matt-lethargic** [comment]
So I've looked into this and the easiest way to do this is [according to this article](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name) is just creating a file in using Visual Studio. does anyone know the effect it would have on the status quo as it is? Will everything just work as normal for the current users?

**Comment by peSHIr** [comment]
As far as I know just adding the signature file has not other effects on
the assembly and its users than enabling the assembly to be registerable in
the global assembly cache, being able to do version based references to the
assembly (being able to have different versions of the assembly installed
while the user specifying the version(s) supported), and no longer getting
errors when trying to reference the assembly from other strongly named
assemblies. Feel free to research on your own.

Op vr 12 jul. 2019 15:34 schreef Matt Lethargic <notifications@github.com>:

**Comment by SimonCropp** [comment]
so you want a pull request for this?

**Comment by xfischer** [comment]
Yep, that would be nice ;)

**Comment by SimonCropp** [comment]
https://github.com/GeoJSON-Net/GeoJSON.Net/pull/127

**Comment by xfischer** [comment]
Thanks again @SimonCropp !
