### ISSUE TITLE
Check if a polygon is a rectangle?

### ISSUE THREAD

**Issue by rijethma** [GeoJSON-Net/GeoJSON.Net#125]
Do you think it'll be beneficial for us to add such an extension method?

**Comment by matt-lethargic** [comment]
Hi @rijethma thanks for the suggestion. I'm actually torn on this idea, it feels like it's moving away from the primary purpose of GeoJSON.Net which is to serialise and deserialise geojson, I'm very much into things doing one thing and doing it well, much like SRP. 

One thing that comes to mind is a new Nuget package that GeoJSON.Net Extenions or something, but then we'd just have one method in it "check if polygon is rectangle" 

Discuss!

**Comment by xfischer** [comment]
Hi @rijethma and @matt-lethargic. This is topology related. It should be more appropriate to use a dedicated library for this (NetTopologySuite, ...)

**Comment by matt-lethargic** [comment]
Agreed @xfischer  and a good point even I use NetTopologySuite for a few things like this!

**Comment by xfischer** [comment]
Just to add a little more context, we are in [Spherical Geometry](https://en.wikipedia.org/wiki/Spherical_geometry).

**Comment by rijethma** [comment]
Thanks for the suggestion! I'll explore the NetTopologySuite library.
