### ISSUE TITLE
Error compiling when installing (latest stable version) 1.1.73 via nuget. Restored to 1.172 resolved it.

### ISSUE THREAD

**Issue by alanmachadouk** [GeoJSON-Net/GeoJSON.Net#128]
Changed to the Latest stable version highlighted in nuget (1.1.73). 
But this causes compiling issues

The type 'IGeometryObject' is defined in an assembly that is not referenced. You must add a reference to assembly 'GeoJSON.Net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

'DbGeography' does not contain a definition for 'ToGeoJSONObject' and the best extension method overload 'EntityFrameworkConvert.ToGeoJSONObject<Point>(DbGeometry)' requires a receiver of type 'DbGeometry'	

etc..

Reverting to 1.172 solved the problem and looking in github the latest stable is shown as 1.172.

So please update nuget back to 1.172 until 1.173 is release and stable
Thanks

**Comment by xfischer** [comment]
Hi @alanmachadouk. Thanks for reporting the issue, and sorry for the inconvenience. 
Are you using GeoJSon.net alone or also one of the GeoJson.Net.Contrib ? If so, which of them ?

**Comment by alanmachadouk** [comment]
Hi,
Using EntityFramework ,MsSqlSpatial, and Wkb

**Comment by dave-schneider-ila** [comment]
Has this been fixed? Running up against same issue. Thanks

**Comment by xfischer** [comment]
Hi ! No it’s not fixed. Sorry 😐 I’ll do it at 1PM Paris Time.
Cheers
Xavier

Le 1 oct. 2019 à 01:05, dave-schneider-ila <notifications@github.com> a écrit :

﻿

Has this been fixed? Running up against same issue. Thanks

**Comment by xfischer** [comment]
Wooot ! All Contrib packages were updated to reference the latest GeoJSON package (1.1.73).

Can you tell me if it's OK ?

**Comment by xfischer** [comment]
@alanmachadouk it is ok now ?
