### ISSUE TITLE
Convert GeoJSON to PBF tiles

### ISSUE THREAD

**Issue by livebird** [GeoJSON-Net/GeoJSON.Net#129]
I need to convert the GeoJSON to PBF vector tiles.

Is there any way to do that?

**Comment by matt-lethargic** [comment]
Not with GeoJSON.Net. The purpose of this library was to enable converting GeoJSON to C# objects and C# objects to GeoJSON. In the spirit of single responsibility this is all it will ever do. A library like Net topology suite might be something you'd want

**Comment by livebird** [comment]
> Not with GeoJSON.Net. The purpose of this library was to enable converting GeoJSON to C# objects and C# objects to GeoJSON. In the spirit of single responsibility this is all it will ever do. A library like Net topology suite might be something you'd want

Thanks for quick reply. 
Can you help me Net topology suite? I posted on that repo but no reply yet.

**Comment by xfischer** [comment]
Hi @livebird and @matt-lethargic.
@matt-lethargic is right, this is not the purpose of GeoJSON.Net. I could be anyhow something in the Contrib project, we would be happy if you can contribute if you find your way.

Nevertheless, I didn't find anything in NTS repo, but here's what I've found so far : 
Specs :
- https://docs.mapbox.com/vector-tiles/specification/

When I search "mapbox vector tiles" in C# repo I have found this : 
- https://github.com/itinero/vector-tiles
You may find useful code to encode PBF tiles. 
May the force be with you.
