### ISSUE TITLE
Feature Request: geometry operators

### ISSUE THREAD

**Issue by JohanMollevik** [GeoJSON-Net/GeoJSON.Net#132]
It would be nice if in a feature version there where geometric operations that could be applied to the parsed objects. I am thinking about operations such as

isIntersecting
isContainedIn

and

intersection
union

etc

**Comment by JohanMollevik** [comment]
@xfischer Ok I see. Is there any examples out there that shows how to combine the libraries?

**Comment by xfischer** [comment]
NetTopology have their own de/serializers : https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON.

So if you go it that direction, you'd not use GeoJSON.net at all. Makes sense ?

**Comment by JohanMollevik** [comment]
@xfischer Yes. Thanks for the explanation
