### ISSUE TITLE
Could not create an instance of type NetTopologySuite.Geometries.Geometry

### ISSUE THREAD

**Issue by ranouf** [GeoJSON-Net/GeoJSON.Net#133]
Hi,

I m using, .Net core 2.2 with :

    <PackageReference Include="GeoJSON.Net" Version="1.1.73" />
    <PackageReference Include="NetTopologySuite" Version="1.15.3" />

Here is my Entity:

    internal class Properties
    {
        [JsonProperty("description")]
        public string Description{ get; set; }
        [...]
    }

    internal class Feature
    {
        [JsonProperty("geometry")]
        public Geometry Geometry { get; set; }

        [JsonProperty("properties")]
        public Properties Properties { get; set; }
    }

    internal class GeoBase
    {
        [JsonProperty("features")]
        public IList<Feature> Features { get; set; }
    }

When I try to deserialize the Json to GeoBase:

```
using (var geoBaseReader = new StreamReader(GeoBaseFilename)){
     var jsonGeoBase = geoBaseReader.ReadToEnd();
     var officialGeoBase = JsonConvert.DeserializeObject<GeoBase>(jsonGeoBase);
}
```

I got this error:

> Could not create an instance of type NetTopologySuite.Geometries.Geometry. Type is an interface or abstract class and cannot be instantiated.

Could you help me to deserialize the Json to GeoBase?

Thanks

**Comment by matt-lethargic** [comment]
Short answer no! Long answer, the error you're getting is very descriptive. By the looks of things you're not using any GeoJSON classes, but you are using `NetTopologySuite.Geometries.Geometry` from NetTopologySuite. I know nothing of this library I'm afraid. Are you trying to deserialize a feature list?

**Comment by matt-lethargic** [comment]
Closing issue as not heard anything
