### ISSUE TITLE
Consolidate csproj and nuspec

### ISSUE THREAD

**Issue by jnyrup** [GeoJSON-Net/GeoJSON.Net#134]
Incorporating the `.nuspec` into the `.csproj` has some nice benefits.
One of the major sale points is that declared dependencies are always in sync.
Currently the `Newtonsoft.Json` dependency and release notes are out of sync.

https://github.com/GeoJSON-Net/GeoJSON.Net/blob/335e9d7d6519718ca2d57eb39be576e300bbdb43/GeoJSON.Net.nuspec#L16

https://github.com/GeoJSON-Net/GeoJSON.Net/blob/335e9d7d6519718ca2d57eb39be576e300bbdb43/src/GeoJSON.Net/GeoJSON.Net.csproj#L18

https://github.com/GeoJSON-Net/GeoJSON.Net/blob/335e9d7d6519718ca2d57eb39be576e300bbdb43/GeoJSON.Net.nuspec#L12

https://github.com/GeoJSON-Net/GeoJSON.Net/blob/335e9d7d6519718ca2d57eb39be576e300bbdb43/src/GeoJSON.Net/GeoJSON.Net.csproj#L14

For examples on the conversion:
* https://github.com/fluentassertions/fluentassertions/pull/1009
* https://github.com/sendgrid/sendgrid-csharp/pull/892

Let me know if you'd like any help.

**Comment by xfischer** [comment]
Hi @jnyrup ! Sounds really great. Could you put that in a PR that would be nice.
@matt-lethargic are you OK with this ?

**Comment by jnyrup** [comment]
Should I target this against the `master` or `2` branch? 
(or both?)

**Comment by matt-lethargic** [comment]
`master` I think we can basically call this feature complete and `2` hasn't really materialised! I'm happy with you creating a PR for this
