### ISSUE TITLE
how to "find a point"

### ISSUE THREAD

**Issue by maruhe** [GeoJSON-Net/GeoJSON.Net#142]
hey there :-)

it looks like I'm to stupid or on a wrok way so please support me:

I found this litte file https://gist.github.com/tschaub/cc70281ce4df5358eac38b34409b9ef9 and as I interprete correct github visualizes this file and when you click somewhere you see the timezone-information

so my question is how can i parse this file and get the node / timezone-info for a point by latitude / longitude or is this not what GeoJSON.Net is made for?

thanks for reading :-)

**Comment by xfischer** [comment]
Hi @maruhe. Thanks for reaching out.

GeoJSON is **only** a parser and a simple type library to have typed GeoJson classes in .Net. Very handful when you have a geoJson as plain text and need to have its counterpart in .net, and vice-versa.

What you are trying to do is perform spatial operations on the GeoJson, and this is not the purpose of the library.
That said, you're left with alternatives:

1. Move to more "spatial" libraries (NetTopology, DotSpatial, ...). They can read GeoJson and then you can perform almost any computations you'll like.
2. Code your point in polygon routine (not recommended, spatial operations are hard on spherical data, and the work has been done already)

**Comment by maruhe** [comment]
sometimes I have to write a quistion to find the answer ;-)
I got happy by finding NetTopologySuite using GeoJSON.NET parser:

here my sample so the next one may can find it faster:

                using GeoJSON.Net;
                using GeoJSON.Net.Feature;
                using NetTopologySuite.Geometries;

                string topology_string = File.ReadAllText("ne_10m_time_zones.geojson"));

                // create NetTopology JSON reader
                var reader = new NetTopologySuite.IO.GeoJsonReader();

                // pass geoJson's FeatureCollection to read all the features
                var featureCollection = reader.Read<GeoJSON.Net.Feature.FeatureCollection>(topology_string);

                // if feature collection is null then return 
                if (featureCollection == null)
                {
                    return;
                }

                // loop through all the parsed featurd   
                for (int featureIndex = 0;
                     featureIndex < featureCollection.Features.Count;
                     featureIndex++)
                {
                    // get json feature
                    var jsonFeature = featureCollection.Features[featureIndex];
                    Geometry geom = null;

                    // get geometry type to create appropriate geometry
                    switch (jsonFeature.Geometry.Type)
                    {
                        case GeoJSONObjectType.Point:
                            break;
                        case GeoJSONObjectType.MultiPoint:
                            break;
                        case GeoJSONObjectType.LineString:
                            break;
                        case GeoJSONObjectType.MultiLineString:
                            break;
                        case GeoJSONObjectType.Polygon:
                            {
                                var polygon = jsonFeature.Geometry as GeoJSON.Net.Geometry.Polygon;

                                List<Coordinate> coordinates = new List<Coordinate>();
                                foreach (var ring in polygon.Coordinates)
                                {
                                    if (ring.IsLinearRing())
                                    {
                                        foreach (var coordinate in ring.Coordinates)
                                        {
                                            coordinates.Add(new Coordinate(coordinate.Latitude, coordinate.Longitude));
                                        }
                                    }
                                }
                                //Add first Point again to be sure to have a closed Polygon
                                //may you have to remove this line:
                                coordinates.Add(new Coordinate(coordinates[0].X, coordinates[0].Y));

                                var poly = new Polygon(new LinearRing(coordinates.ToArray()));
                                if (poly.Contains(new Point(x, y))
                                    FounTimeZoneForPoint();
                            }
                            break;
                        case GeoJSONObjectType.MultiPolygon:
                            break;
                        case GeoJSONObjectType.GeometryCollection:
                            break;
                        case GeoJSONObjectType.Feature:
                            break;
                        case GeoJSONObjectType.FeatureCollection:
                            break;
                        default:
                            throw new ArgumentOutOfRangeException();
                    }
                }

and sure, please close it again, you guys did a great work!

**Comment by xfischer** [comment]
Happy to see that you've found a way around, @maruhe! Thanks!
