### ISSUE TITLE
Cannot use GeoJson.Net.Exceptions

### ISSUE THREAD

**Issue by TruongTran1201** [GeoJSON-Net/GeoJSON.Net#143]
Hi guys.
Im new on GeoJson.Net library.
Now I have a program that deserializes the content of a geojson file into a FeatureCollection object
The program throws an exception when an object inside geojson file doesnt have the attribute "Type" and crash whole program. So I am investigating if the library can just ignore that object (or that kind of error, when an object's format is not matched with geojson object) and continue the process.
 I see the Exceptions namespace in the document, but dont know why I cannot using it. And does is help?
Or you guys can tell me a good way to solve this problem?
Sorry for my bad English.

**Comment by xfischer** [comment]
Hi @TruongTran1201, thanks for reporting your issue there.

GeoJson.Net adheres strictly to GeoJSON specs. The FeatureCollection in your source data is invalid and GeoJSON must raise an exception.
I understand that you need a way to tell "I know, just parse what you can, even if the resulting geometry is inconsistent", but I don't think we will handle such cases in the library now.

Now, what solutions are left to you ?

A. Preprocess the data in javascript or c# with classic Json handling techniques to filter out or fix invalid objects.
B. Fork this repo and modify this class (or similar) https://github.com/GeoJSON-Net/GeoJSON.Net/blob/79b025ae6ee6f8a0c5ddd90cdb20121d7ffee989/src/GeoJSON.Net/Converters/GeoJsonConverter.cs to handle such cases.

Hope that this will help.

**Comment by TruongTran1201** [comment]
Thanks @xfischer 
I will try it
