### ISSUE TITLE
.net core api does not deserialize correctly with default System.Text.Json library

### ISSUE THREAD

**Issue by jrowe88** [GeoJSON-Net/GeoJSON.Net#144]
This may need to just be documented, but in .NET Core 3 the System.Text.Json library is used by default.  As a result, returning some GeoJSON objects from an API will not deserialize correctly--for example, a "Feature" does not include any of the Geometry information.  To fix this you need to reconfigure you asp.net api to use Newtonsoft:

1) add the "Microsoft.AspNetCore.Mvc.NewtonsoftJson" NuGet Package
2) add "services.AddControllers().AddNewtonsoftJson();" to your service configuration.

**Comment by xfischer** [comment]
Hi @jrowe88 and thanks for the input.
Yes, you are right, I'll add that to the readme.
