### ISSUE TITLE
How to get the area of a geometry?

### ISSUE THREAD

**Issue by donnyv** [GeoJSON-Net/GeoJSON.Net#145]
The Polygon class of NetTopologySuite has an "area" property but it looks like GeoJSON.Net doesn't have one. How would I do that?

**Comment by xfischer** [comment]
Hi @donnyv and thanks for reaching out.

GeoJSON.net is not a topology library. You can serialize/deserialize Json and have GeoJSON typed object with close adherence to the GeoJSON specs.

Can I ask what do you need Area for ? I may be able to suggest a solution for your needs.

**Comment by donnyv** [comment]
Trying to calculate the acreage of a polygon. 

Is there a way to turn GeoJSON.Net polygon to a NetTopologySuite polygon?

**Comment by xfischer** [comment]
One straightforward way would be go 100% to NetTopology, they have GeoJson support via a dedicated NuGet.

**Comment by xfischer** [comment]
Closing as this thread muted itself unconsciently
