### ISSUE TITLE
The library might not be aligned with the GeoJSON RFC 7946 standard

### ISSUE THREAD

**Issue by deepforest** [GeoJSON-Net/GeoJSON.Net#150]
Hi,
I'm creating a C# object as follows:
`var feature = new Feature<Point>(new Point(new Position(lat, lon))),`
When I'm serializing it to JSON (using .NET 3.1 JSON serializer), I'm getting:
`{
        "type": "Feature",
        "id": null,
        "geometry": {
            "type": "Point",
            "coordinates": {
                "altitude": null,
                "latitude": 31.913118941395805,
                "longitude": 34.79653358459473
            },
            "boundingBoxes": null,
            "crs": null
        },
        "properties": {},
        "boundingBoxes": null,
        "crs": null
    }`

Problem is that based on the standard, `coordinates` should be an array with no component names.
Using Newtonsoft JSON serializer, works fine. It looks like a Newtonsoft JSON converter ignored by the .net core 3.x serializer.

Thanks.

**Comment by matt-lethargic** [comment]
Hi @deepforest thanks for this. I've been meaning to look at the .Net Core 3 things regarding GeoJSON.Net, seems this is going to be an on-going issue. Trying to find the time at the moment isn't good for me :-(

**Comment by SebastianStehle** [comment]
It makes it very clear in the Readme, that it depends on Json.Net, I think. If you want to support System.Text.Json you have to write a converter.
