### ISSUE TITLE
Incorrectly coupling to geographic coordinate systems

### ISSUE THREAD

**Issue by jsiemensLatitudegeo** [GeoJSON-Net/GeoJSON.Net#158]
The IPosition interface is defined using Latitude, Longitude, and the Point constructore requires an IPosition. That means that all Points are required to use Latitude, Longitude, which is valid for a geographic coordinate system. But this doesn't account for projected coordinate systems, where the coordinates are X, Y or Easting, Northing.

From the GeoJSON spec:

[A.1](https://datatracker.ietf.org/doc/html/rfc7946#appendix-A.1).  Points

   Point coordinates are in x, y order (easting, northing for projected
   coordinates, longitude, and latitude for geographic coordinates):

     {
         "type": "Point",
         "coordinates": [100.0, 0.0]
     }

**Comment by orbitzhan** [comment]
我已收到您的来信 谢谢！

**Comment by jsiemensLatitudegeo** [comment]
So it does. That's quite interesting. Nevertheless, section 4 also states:

"However, where all involved parties have a prior arrangement, alternative coordinate reference systems can be used without risk of data being misinterpreted."

In other words, there is no way in the spec to specify the coordinate system in the json. It's just a set of "coordinates". Nevertheless, it's possible to construct json where the coordinates are in some alternate coordinate system. So the spec doesn't explicitly prevent it. But the GeoJSON.Net api makes it akward.

In any event, it's no skin off my back; I've already moved on. I decided to roll my own solution, rather than use GeoJSON.Net due to this issue.

**Comment by xfischer** [comment]
Just for the sake of the correctness, Json is a serialization format, so when "all involved parties have a prior arrangement", they cannot still change the format, but consider that the data serialized is not schema-compliant (ie eastings stored in longitude)
