### ISSUE TITLE
Target frameworks: why so many?

### ISSUE THREAD

**Issue by YaroslavKormushyn** [GeoJSON-Net/GeoJSON.Net#159]
Is there a specific need to have so many target frameworks?
I was under the impression that it's easier to target the lowest possible version, which is compatible with any newer version by design.
So this way we would have `net35` instead of `net35;net40;net45;` and `netstandard1.0` instead of `netstandard1.0;netstandard1.1;netstandard2.0;netstandard2.1;`.

I may be missing something here, so please feel free to point out the reasons for this set of target frameworks.

**Comment by matt-lethargic** [comment]
This is just a legacy thing from before I was owner. I think the original idea was to copy [Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json) as this package follows that to some extent

**Comment by YaroslavKormushyn** [comment]
@matt-lethargic I don't know if having different reverse-compatible target frameworks actually makes a difference for end users, so I'd need some time to research that. So far my assumption was that [frameworks after EOL](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) (so far this would be all .NET Framework 3.5/4.0/4.5) should be deprecated in favor of .NET Standard or .NET 2n+1 (major LTS). This way we don't try catering to a minor percentage of users still using deprecated frameworks, but still have ways to introduce new QoL features in new releases without much trouble.

Also, expected to see a `v2` branch here for breaking changes / major updates, but there's only `master` in here. Did I miss something?

**Comment by janusw** [comment]
We have done some consolidation and updating of the target frameworks in #180, so I guess we can close this issue.
