### ISSUE TITLE
The supported version of the dependency Newtonsoft.Json has a High Severity Vulnerability.

### ISSUE THREAD

**Issue by mc1903** [GeoJSON-Net/GeoJSON.Net#163]
Hi,

A high severity vulnerability exists with all versions of the dependency Newtonsoft.Json prior to version 13.0.1. https://github.com/advisories/GHSA-5crp-9r3c-p9vr

I am unable to load GeoJSON.Net version 1.2.22-rc (latest) with any version of Newtonsoft.Json after version 10.0.3. It just errors with the missing dependency.

Please can you consider updating GeoJSON.Net to support the latest version of Newtonsoft.Json

Thanks
M

**Comment by matt-lethargic** [comment]
Am doing so now 👍

**Comment by matt-lethargic** [comment]
I've released [v1.3.3-rc ](https://www.nuget.org/packages/GeoJSON.Net/1.3.3-rc) and put a reminder in my diary to release a non-rc version in a month if I have no issues

**Comment by mc1903** [comment]
Thank you @matt-lethargic.

I have just tested version 1.3.3-rc (\net45) with Newtonsoft.Json version 13.0.1 (\net45) and the missing dependency error message longer appears.

Cheers,
M

**Comment by matt-lethargic** [comment]
I've not got net45 setup/working on my machine only net451. Could you supply some more information like stack trace and/or some code?
