### ISSUE TITLE
Function to calculate the new coordinates from given base coordinates, along with a distance & a bearing?

### ISSUE THREAD

**Issue by mc1903** [GeoJSON-Net/GeoJSON.Net#164]
Is there a function in GeoJSON.Net that for a given set of base coordinates, along with a distance, a bearing (?azimuth?) and/or an optional altitude; will calculate the new end point coordinates?

Any advice/examples would be appreciated.

Thanks
M

**Comment by matt-lethargic** [comment]
GeoJSON was built just to serialize and deserialize GeoJSON so that sort of functionality is out of scope.
I've used [NetTopologySuite](https://github.com/NetTopologySuite/NetTopologySuite) in the past, think it might be able to help you

**Comment by mc1903** [comment]
Thanks for the quick reply and pointer @matt-lethargic. Much appreciated.
