### ISSUE TITLE
Be able to deserialize to IGeoJSONObject object

### ISSUE THREAD

**Issue by XVincentX** [GeoJSON-Net/GeoJSON.Net#17]
The library should be able to create an interface of IGeoJSONObject type inferring it's real type from json payload!

**Comment by blachniet** [comment]
Was support for this ever added? I don't see a way to do it, but maybe I'm just missing it.

**Comment by jbattermann** [comment]
Nope @blachniet - sorry to say but nothing has changed in that regard..

**Comment by matt-lethargic** [comment]
Seems this was put in in PR51, @XVincentX happy to close?

`JsonConvert.DeserializeObject<IGeoJSONObject>(json, new GeoJsonConverter());`

**Comment by matt-lethargic** [comment]
Closing

**Comment by XVincentX** [comment]
With more than 2 years to be honest I do not recall it anymore.

**Comment by matt-lethargic** [comment]
Lol, well it works now anyway!
