### ISSUE TITLE
NuGet stable release

### ISSUE THREAD

**Issue by YaroslavKormushyn** [GeoJSON-Net/GeoJSON.Net#170]
The last stable NuGet release is from 6/5/2020.
The last RC is from 10/28/2022.
What's the reason the last RC cannot be a stable release?

**Comment by janusw** [comment]
> What's the reason the last RC cannot be a stable release?

I was wondering about this as well.

> The last RC is from 10/28/2022.

This is 1.3.6-rc. It has 70k downloads on nuget.org by now, and only 9 issues have been opened on GitHub since then. That sounds pretty "stable" to me ;)

The next release should be a proper 1.3.7 IMHO.

**Comment by janusw** [comment]
Also I'll note that ...
* There are unfortunately no release tags since `1.2.15`, and it's not obvious from which commits the releases have been built.
* The `<Version>` in the csproj has not been updated consistently and is still at `1.2.16`.

**Comment by janusw** [comment]
>     * There are unfortunately no release tags since `1.2.15`, and it's not obvious from which commits the releases have been built.

This also affects the version number of the nupkgs which are automatically built via GitHub Actions (we use `git describe` for this, which is based on tags).

E.g. the version that is generated for the GHA build in PR #179 is `1.2.15-36-g458a2b7`, which is pretty misleading. We'd need a tag for the latest release (currently `1.3.6-rc`) to fix that.

**Comment by xfischer** [comment]
Yes I think it's due to some tests being made during the past years, and all maintainers were very busy. I don't know where the 1.3.6 tag comes from, maybe a local branch out in the wild.
Anyway this leaves us with a version gap, so the next stable should be 1.3.6...

**Comment by janusw** [comment]
> Yes I think it's due to some tests being made during the past years, and all maintainers were very busy. I don't know where the 1.3.6 tag comes from, maybe a local branch out in the wild.

Judging from the date, I'd assume that 1.3.6-rc corresponds to commit 24be0a8427681be3bb1093420d21d62cbbf285d1.

(Note that all 1.3.x packages were published on the same day.)


> Anyway this leaves us with a version gap, so the next stable should be 1.3.6...

Maybe one should go for a clean slate and make it 1.4.0? The time gap to 1.3.6-rs is huge ;)

@xfischer Is it feasible to prepare a new release soon? I can help with it, if you want.

One remaining thing I could imagine would be to update to .NET 6 (since .NET 3.1 and 5 are out of support by now), and maybe some dependency updates (like #168). Anything else that should be included?

**Comment by janusw** [comment]
> > Yes I think it's due to some tests being made during the past years, and all maintainers were very busy. I don't know where the 1.3.6 tag comes from, maybe a local branch out in the wild.
> 
> Judging from the date, I'd assume that 1.3.6-rc corresponds to commit [24be0a8](https://github.com/GeoJSON-Net/GeoJSON.Net/commit/24be0a8427681be3bb1093420d21d62cbbf285d1).

FYI, I have set a tag for that one now, and for 1.2.16 (which was easy to indentify as well).

**Comment by janusw** [comment]
We have prepared a stable release 1.4.0 (see #181). Closing.
