### ISSUE TITLE
Coordinates type doesn't parse properties

### ISSUE THREAD

**Issue by algorni** [GeoJSON-Net/GeoJSON.Net#171]
Hi, i've this coordinates JSON

{"coordinates":[8.940176,44.399784,0],"type":"Point","properties":{"verticalAccuracy":0,"horizontalAccuracy":0,"timestamp":"Tue May 02 16:15:11 UTC 2023"}}

When i deserialize with this:

Point gatewayPosition =  JsonConvert.DeserializeObject<Point>(geoJson);

And try to serialize again it looses the properties:

{
  "type": "Point",
  "coordinates": [
    8.940176,
    44.399784,
    0.0
  ]
}

**Comment by xfischer** [comment]
Hi @algorni, thanks for reporting this. I'll have a look, this looks like a bug.

**Comment by xfischer** [comment]
@algorni, properties are only permitted on Feature or FeatureCollection, not on individual geometries. 
So try with this and it should work fine : 

```json
{
  "type":"Feature",
  "geometry":{
    "type":"Point",
    "coordinates":[
      8.940176,
      44.399784,0
    ]
  },
  "properties":{
    "verticalAccuracy":0,
    "horizontalAccuracy":0,
    "timestamp":"Tue May 02 16:15:11 UTC 2023"
  }
}
```

**Comment by janusw** [comment]
As pointed out by @xfischer, the properties need to be in the feature, not the geometry. Closing.
