### ISSUE TITLE
Get Feature Properties from inheritance object

### ISSUE THREAD

**Issue by totpero** [GeoJSON-Net/GeoJSON.Net#174]
Hi,
I try to serialize inheritance objects properties but only the first level of the object properties is serialized.

I have Inheritance classes like this:

```
public abstract class GeoJsonCircleStyleResult {
   public GeoJsonNodeStyleType NodeType => GeoJsonNodeStyleType.Circle;
   public abstract string NodeFillColor { get; set; }
   public string NodeTextColor { get; set; } = "#000000";
}
```

```
public class MyDocumentGeoJsonResult : GeoJsonCircleStyleResult
{
    public Guid Id { get; set; }
    public string Description { get; set; }

    public decimal CoordonateX { get; init; }
    public decimal CoordonateY { get; init; }
   public override string NodeFillColor { get; set; } = "#03a9f4";
}

```
And I generate my FeatureCollection like this:

```
var features = dbDocumentList
    .Select(s =>
        new Feature(
            new Point(new Position(decimal.ToDouble(s.CoordonateY), decimal.ToDouble(s.CoordonateX))),
            new MyDocumentGeoJsonResult
            {
                Id = s.Id,
                Description  = s.Description,
                CoordonateX  = s.CoordonateX,
                CoordonateY  = s.CoordonateY,
            },
            s.Id.ToString()
        )
    );
var f = new FeatureCollection(features.ToList())
{
    CRS = new NamedCRS(GisLayersConstants.GeoJosn.EpsgStereo70NamedCrs)
};
```
and the result is:

```
{
	"type": "FeatureCollection",
	"features": [
		{
			"type": "Feature",
			"id": "ce26c738-3a04-4685-137f-08dc0926e451",
			"geometry": {
				"type": "Point",
				"coordinates": [
					433112.0736298195,
					467858.3951030532
				]
			},
			"properties": {
				"Description": "sample text description",
				"CoordonataX": 0.0,
				"CoordonataY": 0.0,
				"NodeFillColor": "#03a9f4",
			}
		}
	],
	"crs": {
		"properties": {
			"name": "urn:ogc:def:crs:EPSG::3844"
		},
		"type": "name"
	}
}
```
Is missing the base `NodeTextColor` property.

This is happened because [here](https://github.com/GeoJSON-Net/GeoJSON.Net/blob/e6d5fa78fa4ee058500d41e9e6867861d629b0c9/src/GeoJSON.Net/Feature/Feature.cs#L154C56-L154C56) is parsed only first level of the object public properties.

**Comment by xfischer** [comment]
Hi @totpero. Thanks for reporting this. 
Spec states that properties could be any JSON object. 
GeoJSON.Net is wrong when assuming that properties could be represented as Key/Value pairs. 

What would you expect ? 
- Flatten your JSON object ? This would require a try/guess hierarchy game when deserializing which in my opinion is not clean
- Properly treat properties as any JSON payload, but would required maintaining actual Dictionnary getters for users only storing key/values. This is my preferred option and we could move forward. 

@matt-lethargic Any thoughts?

**Comment by totpero** [comment]
Hi @xfischer , thanks for your prompt response.
I expect key/value dictionary like now but in this dictionary to include the properties from the base classes.
In my json is missing the `NodeTextColor` property like this:

```
"properties": {
	"Description": "sample text description",
	"CoordonataX": 0.0,
	"CoordonataY": 0.0,
	"NodeFillColor": "#03a9f4",
	"NodeTextColor": "#000000",
}
```
This is my purpose to keep my classes more clean code to use inheritance and the properties serialized to contain some mandatory c# properties and values.

**Comment by matt-lethargic** [comment]
Hey all. Sorry I've not been keeping up with this, I'll try and have a read this week and comment properly
