### ISSUE TITLE
There is a problem getting the value of type

### ISSUE THREAD

**Issue by MangMax** [GeoJSON-Net/GeoJSON.Net#176]
When I try to construct a class or serialize a string, my type always returns the enumerated value instead of the string, why is that, for example Feature, I get a value of 7, how can I return his string instead of the enumerated value?
![image](https://github.com/GeoJSON-Net/GeoJSON.Net/assets/68525017/6d97aded-f4d2-4cc6-b39a-e6cc16605414)

**Comment by xfischer** [comment]
Hi @MangMax, you can use the `JsonSerializer`'s builtin `StringEnumConverter` like this : 

```csharp
var mangMaxJson = JsonConvert.SerializeObject(feature, converters: new StringEnumConverter());
```

**Comment by MangMax** [comment]
Thanks, configured it in the webapi project, it's fixed!
