### ISSUE TITLE
Feature without geometry is rejected

### ISSUE THREAD

**Issue by janusw** [GeoJSON-Net/GeoJSON.Net#178]
GeoJSON.Net currently does not accept features that have no geometry member (when deserializing):

```
Newtonsoft.Json.JsonSerializationException: Required property 'geometry' not found in JSON.
```

The GeoJSON RFC says (see https://datatracker.ietf.org/doc/html/rfc7946#section-3.2):

```
   o  A Feature object has a member with the name "geometry".  The value
      of the geometry member SHALL be either a Geometry object as
      defined above or, in the case that the Feature is unlocated, a
      JSON null value.
```

So, an 'unlocated' feature with `null` geometry is indeed allowed.

While an absent/undefined `geometry` member is technically not mentioned here, I don't see much difference to a `null` geometry: In the end you have an unlocated feature without any geometry information.

So one could argue that this case is allowed by the GeoJSON RFC. And even if it was not allowed, the library could accept it as an extension (and generate an unlocated feature for it).

**Comment by xfischer** [comment]
Agreed @janusw and thanks for summarizing that.
We should fix that. Do you have something or do you want me to have a look ?

**Comment by janusw** [comment]
I think I can prepare a patch which addresses this today, and I'd be thankful for a review then 🙂
