### ISSUE TITLE
Deserialization for interior polygon

### ISSUE THREAD

**Issue by puregame** [GeoJSON-Net/GeoJSON.Net#20]
The PolygonConverter only works with single-layer polygons, any polygon with a hole will not work with this method.

I will be creating a solution to this.

**Comment by russcam** [comment]
@puregame do you have an example?

**Comment by puregame** [comment]
This is from the GeoJSON specification: *"For type "Polygon", the "coordinates" member must be an array of LinearRing coordinate arrays. For Polygons with multiple rings, the first must be the exterior ring and any others must be interior rings or holes."*

I haven't looked at this in over 5 months, take a look at my changes here for my solution to this: https://github.com/puregame/GeoJSON.Net

See this as an example of a proper polygon: https://gist.github.com/puregame/f6683ac0261727832861

**Comment by russcam** [comment]
@puregame The latest in master deserializes the example as expected using 

```c#
var featureCollection = JsonConvert.DeserializeObject<FeatureCollection>("[json string here]");
```
the polygon contains two linestrings that are linear rings, with the first linestring representing the exterior ring.

**Comment by puregame** [comment]
Looks like it was fixed a month after I opened the issue...

https://github.com/GeoJSON-Net/GeoJSON.Net/commit/d4c2921188d0c572b3c5af07e79827c9e183bfa7

If you looked at the commit history you would see this easily.

**Comment by russcam** [comment]
Ok, so this issue can be closed.

**Comment by jbattermann** [comment]
Thanks guys!
