### ISSUE TITLE
Can't parse LineString

### ISSUE THREAD

**Issue by tonyIDMI** [GeoJSON-Net/GeoJSON.Net#37]
Trying to parse the json below, errors with "Value cannot be null."

{ "type": "LineString","coordinates": [ [-81.586856, 41.102725], [-81.586856, 41.102725] ]}

Trying to parse the above string with:

JsonConvert.DeserializeObject<GeoJSON.Net.Geometry.LineString>(lineString, new GeoJSON.Net.Converters.LineStringConverter());

**Comment by welshrat77** [comment]
Yes I am having the exact same issue.

Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'GeoJSON.Net.Geometry.IPosition' because the type requires a JSON object (e.g. {"name":"value"})

'type':'Feature',
         'geometry':{  
            'type':'LineString',
            'coordinates':[[-4.273188159685178, 53.13877356151247], [-4.272481994040332, 53.1391946944829]]
         },
         'properties':{  
            'prop0':'value0',
            'prop1':{ 'this':'that' }
         }

All other types seem ok so far, major issue for me as the source data I have is all linestrings :-)

**Comment by jbattermann** [comment]
Hey there @welshrat77 and @tonyIDMI - thanks for reporting this! I am currently swamped & cannot fix this myself, but if one of you fixes it and sends over a PR, I'll  gladly merge it in!

**Comment by russcam** [comment]
I'm working on quite a few updates to the library, one of which fixes this. Will send a PR when ready, should be in the next few days

**Comment by jbattermann** [comment]
Awesome, thanks @russcam !

**Comment by afradin** [comment]
I'm glad to see I'm not the only one having this issue, I spend some time trying to figure out what I did wrong and it was driving me crazy.

@russcam  Thanks, I'm waiting for your updates !

**Comment by russcam** [comment]
Nearly there, hopefully send the PR tomorrow (Australian time). 

@jbattermann I've made quite a few changes; would you prefer me to split them out into separate commits of related changes or would you be happy with one well described commit? a breakdown of changes

1. Refactored existing unit tests into separate classes and files, each responsible for testing only one system/thing
2. Swapped out MSTest for NUnit to allow ease of writing parameterized tests
3. Added missing test cases
4. Implemented Equality members on all geometry objects
5. Optimized serialization/deserialization in Converters
6. Implemented missing serialization/deserialization implementations for geojson types e.g. MultiPoint, GeometryCollection

Just finishing off some changes to CRS types to honour a null crs in the json representation as an unspecified CRS and no crs to mean the default CRS.

**Comment by afradin** [comment]
Quite an impressive update, thanks ! The LineString parsing works perfectly on my end.

**Comment by russcam** [comment]
Good stuff!

**Comment by jbattermann** [comment]
@afradin @russcam is it ok to close this issue with the changes @russcam brought in?

**Comment by afradin** [comment]
That's fine with me.

**Comment by jbattermann** [comment]
Perfect, thanks you two!
