### ISSUE TITLE
Coordinate Order

### ISSUE THREAD

**Issue by Freddixx** [GeoJSON-Net/GeoJSON.Net#38]
Hi,

working on a fork of your project I noticed that the order you're using in your `GeographicPosition` class is following:

Latitude, Longitude, Altitude

However the documentation requires the following order:

> Point coordinates are in x, y order (easting, northing for projected coordinates, longitude, latitude for geographic coordinates):

And:

> A position is represented by an array of numbers. There must be at least two elements, and may be more. The order of elements must follow x, y, z order (easting, northing, altitude for coordinates in a projected coordinate reference system, or longitude, latitude, altitude for coordinates in a geographic coordinate reference system).

http://geojson.org/geojson-spec.html

Is your order wrong or am I?

Cheers,
Fred

**Comment by perliedman** [comment]
The .NET API uses lat/lng order, but if you look at the code that actually serialize and deserialize to JSON, it will output/parse coordinates in lng/lat order, as specified by the GeoJSON spec.

Look at `PointConverter`, for example:

https://github.com/jbattermann/GeoJSON.Net/blob/master/src/GeoJSON.Net/Converters/PointConverter.cs#L37

```C#
var coordinateArray = new JArray(coordinates.Longitude, coordinates.Latitude);
if (coordinates.Altitude.HasValue && coordinates.Altitude != 0)
    coordinateArray = new JArray(coordinates.Longitude, coordinates.Latitude, coordinates.Altitude);

serializer.Serialize(writer, coordinateArray);
```

**Comment by Freddixx** [comment]
Hi Per,

now that you pointed it out I see it.. Luckily I only had to change two lines of code. 

Thanks for the quick answer!
