### ISSUE TITLE
CRS type issue

### ISSUE THREAD

**Issue by Distem** [GeoJSON-Net/GeoJSON.Net#40]
Hi, we are having an issue with GeoJSON.net and openlayers 3. The problem is that GeoJSON.Net provides CRS.types with upper-case first letter (i.e. "Name") when openlayers is expecting a lowercase string "name" and throws an CRS.type invalid exception. And the GeoJSON spec says - " the value of its "type" member must be the string "name"/"link" ". I guess the keyword here is "must" and the same issue might be applicable when working with other libraries as well.

**Comment by ondrasvoboda** [comment]
Hi, I'm having the same problem when working with openlayers.

**Comment by jbattermann** [comment]
@Distem & @ondrasvoboda thanks for reporting the issue, but I can currently spend hardly any time on this project / library. However, if you send over a PR with a fix, I'll gladly merge it in and have the new version pushed asap.
