### ISSUE TITLE
Json .NET (NewtonSoft.Json) updated to 7.0.1 version

### ISSUE THREAD

**Issue by TechnoDexx** [GeoJSON-Net/GeoJSON.Net#41]
Json .NET (NewtonSoft.Json) updated to 7.0.1 version
It's important. Thank you.

**Comment by matt-lethargic** [comment]
This was done early last year so closing. 
[Commit](https://github.com/GeoJSON-Net/GeoJSON.Net/commit/3a429b46d8e9ac7fd20abf34972abffdb366cc6c)
