### ISSUE TITLE
Cant binary serialize parent objects containing feature (or likely other objects)

### ISSUE THREAD

**Issue by JamesBrown2778** [GeoJSON-Net/GeoJSON.Net#42]
I would like to use the feature object and pass it to another program that would serialize to json. But whilst i would previously serialize the parent object to binary while passing, now i cant.

Is it possible to just add the [Serializable] attribute where needed?

Thanks :)

**Comment by matt-lethargic** [comment]
Hi @JamesBrown2778, is this still something you are interested in? GeoJSON.Net was built to use Newtonsoft.Json, as far as I know putting the [Serializable] attribute on the classes will have unwanted outcomes when serializing (exposing private fields etc) if not done with consideration for all things. Let me know if you want us to look into this, if not we'll close the Issue.

**Comment by matt-lethargic** [comment]
Closing
