### ISSUE TITLE
No Json.NET version in the nuspec

### ISSUE THREAD

**Issue by jkallay1** [GeoJSON-Net/GeoJSON.Net#47]
The GeoJSON.Net nuspec doesn't include any version information about the version of Json.NET it depends on. This is important, given the ubiquity of Json.NET, and therefore the likelihood of multiple (and therefore, possibly conflicting) transitive dependencies. You should use the _minimum_ version of Json.NET that works.

**Comment by jbattermann** [comment]
Thanks for reporting & yeah.. something went wrong there last night. I'll fix it and push a fix asap

**Comment by jbattermann** [comment]
Alright - version 0.1.43 pushed that specifies the correct Json.Net version and is placed in the correct pcl / lib folder.

Thanks!
-J

**Comment by jkallay1** [comment]
Are you _certain_ that GeoJSON.Net _requires_ Json.Net version 8.0.2 (the very latest version)? As I stated when opened the issue, you should require the minimum version that would allow the code to compile and behave as expected (i.e. pass all tests).
