### ISSUE TITLE
Duplicate class MultiPointConverter.cs

### ISSUE THREAD

**Issue by durandt** [GeoJSON-Net/GeoJSON.Net#48]
Hi, 

I am not sure if that's a big issue but I noticed that there are two `MultiPointConverter` classes. 
One in `GeoJSON.Net.Converters` and one in `GeoJSON.Net.Geometry`. 
Can be a little confusing when reading quickly the library's contents. 

Regards,

**Comment by jbattermann** [comment]
Good morning Thibault,

oh my yeah... that must have slipt in with one of the past contributions and I didn't ntoice.

Thanks for reporting & I'll check which one is the 'correct' one later today..

Cheers,
-J

**Comment by matt-lethargic** [comment]
There is now (and some would say can be!) only one.
Code is live so closing
