### ISSUE TITLE
does it possible to convert a wkt format geometry to geojson using geojson.net?

### ISSUE THREAD

**Issue by dyh333** [GeoJSON-Net/GeoJSON.Net#49]
does it possible to convert a wkt format geometry to geojson using geojson.net?

**Comment by matt-lethargic** [comment]
This is something I was thinking of as I've needed this in the past. It would prob go in the [Contrib ](https://github.com/GeoJSON-Net/GeoJSON.Net.Contrib) project though. I may have a look at doing this. @xfischer thoughts?

**Comment by xfischer** [comment]
Thanks @matt-lethargic, this is really what Sql Server Types are good at (with some love), via 
`var sqlGeom = SqlGeometry.Parse(new SqlString(wkt), srid);`
and using GeoJSON.Net.Contrib.MsSqlSpatial, with 
`var geoJsonObject = sqlGeom.ToGeoJSONGeometry();`
@dyh333 You can see an example in [GeoJSON.Net.Contrib.MsSqlSpatial tests](https://github.com/GeoJSON-Net/GeoJSON.Net.Contrib/blob/master/src/GeoJSON.Net.Contrib.MsSqlSpatial.Test/ToGeoJSONGeometryTests.cs)

Maybe it would be useful to add some static class like WKTHelper (or GeoJSONFactory), for example: 
`// GeoJSON.Net.Contrib.MsSqlSpatial referenced in project`
`var geoJson = GeoJSONFactory.FromWKT(sring wkt, int srid);`
or something like that ? What do you think ?

**Comment by dyh333** [comment]
@xfischer thanks. i will try it.

**Comment by xfischer** [comment]
To cleary answer the question :
- It is not possible via GeoJSON.Net
- It is possible with GeoJSON.Net.Contrib.MsSqlSpatial and Microsoft.SqlServer.Types

I'm going to add a GeoJSON factory int the contrib that can handle Wkt and generate GeoJSON objects.

Please let me know how you're doing with your tests.

**Comment by matt-lethargic** [comment]
@xfischer I forgot about the MS Spatial stuff, sounds like you got this! I would say though that I'm not sure on the name 'factory' as it doesn't really follow the Factory Pattern and may get confused. Open to thoughts though.

**Comment by xfischer** [comment]
@matt-lethargic OK with not using Factory. Do you have any ideas ?
Meanwhile I'll put it int `MsSqlSpatialConvert.FromWkt(string wkt)`

**Comment by matt-lethargic** [comment]
Lol nope, no ideas!!! :-)

**Comment by xfischer** [comment]
Here it is : https://github.com/GeoJSON-Net/GeoJSON.Net.Contrib#wkt-helper-examples.
Feel free to suggest other name or usage if you want.

**Comment by matt-lethargic** [comment]
WktConvert ?!

**Comment by xfischer** [comment]
@matt-lethargic That's an idea !! Let's see if someone comes up with another suggestion. @hanssens ?

**Comment by xfischer** [comment]
@matt-lethargic Done !

**Comment by matt-lethargic** [comment]
Cool. @dyh333 are you happy for us to close this issue now?

**Comment by dyh333** [comment]
@matt-lethargic @xfischer  thanks you two very much !
