### ISSUE TITLE
Reintroduce support for Silverlight

### ISSUE THREAD

**Issue by pwain** [GeoJSON-Net/GeoJSON.Net#55]
Hi,

I noticed you moved from Profile344 to Profile259 back in January. A major side-effect of this is that the PCL can no longer be used by Silverlight projects.

How would you feel about reinstating Profile344? I don't think its a big job - mostly just avoiding a few of the newer reflection APIs. I can put together a PR, but I thought I'd just check in first in case there are other reasons why this wouldn't be a good idea.

Cheers,

Peter.

**Comment by matt-lethargic** [comment]
Sorry no one has replied to this, this is something I'm looking at currently for version 1.0.1 which hopefully will be the next release.

**Comment by rjhernandez** [comment]
Wouldn't this be addressed by refactoring the project to be a `.NET Standard Library`? 
See https://docs.microsoft.com/en-us/dotnet/standard/library#net-platforms-support

I already have a Fork that I can PR into this repository if interested.
See https://github.com/rjhernandez/GeoJSON.Net/tree/net-standard-1.1

**Comment by matt-lethargic** [comment]
Hi @rjhernandez I've been pulled away from this project at the moment, I was looking into multi-targeting the GeoJSON.Net library and one of those targets was NetStandard. I'll take a look at your PR when I get back to this and hopefully will get a new 'all singing' version out soon.

**Comment by matt-lethargic** [comment]
I'm closing this issue as it's over a year old and we're making steps towards supporting more platforms unless anyone has objections
