### ISSUE TITLE
Setting to disable camelCase serialisation on feature properties names.

### ISSUE THREAD

**Issue by andresteyn** [GeoJSON-Net/GeoJSON.Net#59]
Hi 

Great software! My apologies if this is a duplicate issue. 

I have the following situation:

I am using your library to pull data out of a database and serve it to a client. However, the client is expecting the feature property names to be the same as those in the database (case-sensitive) e.g. Name, Area, Region.

Is it possible to place a setting on the serialiser to ignore case for property names only?

**Comment by andresteyn** [comment]
I resolved this issue by changing my global serialiser setting using the technique provided here:
http://stackoverflow.com/questions/24143149/keep-casing-when-serializing-dictionaries

I am going to close this issue. Apologies if it is poor etiquette to close own issues.

**Comment by jbattermann** [comment]
No worries @andresteyn - glad you found a solution for your problem (which is exactly what I'd have suggested) 👍
