### ISSUE TITLE
GeographicPosition private setters prevents Deserialization

### ISSUE THREAD

**Issue by nadavpld** [GeoJSON-Net/GeoJSON.Net#60]
I was trying to deserialize (with Newtonsoft's JsonConvert) a GeographicPosition object which I recieved from my server unsuccessfully.
I even tried something much more simple, creating a new GeographicPosition object, serializing and deserializing it - something which also "failed", the GeographicPosition object constructed with values (1,2,3), serialized into a correct json object and got deserialized into a GeographicPosition (0,0,0).
After some research I noticed that GeographicPosition class is making use of private setters which were the ones that prevented the correct deserialization, removing them solved the issue.
So, my questions are : 
1. Why GeographicPosition is using private setters ? What's the benefit ?
2. Do I expose myself to any kind of vulnerabilities by setting them as non-private methods ? 
3. Are there any alternative methods ? good practices ?

Thank you.

**Comment by jbattermann** [comment]
There are (passing) Tests that serialize and deserialize GeographicPosition instances (see i.e. https://github.com/GeoJSON-Net/GeoJSON.Net/blob/8f9fbd97a9ad85468fe34a84fa74270c84ee855b/src/GeoJSON.Net.Tests/Geometry/PolygonTests.cs#L241) so I suspect it might have something to do with how you configure / use Json.Net. A quick search using your favourite search engine for "Json.net and Private Property Setters" does provide all information needed to understand how Json.Net handles these and how to include them in (de)serialization, i.e. http://danielwertheim.se/json-net-private-setters/.

**Comment by matt-lethargic** [comment]
@nadavpld Can this be closed now?

**Comment by nadavpld** [comment]
I couldn't make it work at the end and had to leave the setters non-private because it was too much overhead for such a simple task, Unfortunately I didnt have time to get back to it.
Its been few months since I had a look at this piece of code, I will give it another try and let you know (in private?).

**Comment by matt-lethargic** [comment]
Ok, I'll close this for now, if you do go back to it feel free to re-open this issue, or indeed open another one and post the json you are trying to deserialize and a code snippet and I can have a proper look. All of our deserialization tests work fine with private setters so it would be interesting to see whats going on if it's still the case.
