### ISSUE TITLE
Feature equality problem

### ISSUE THREAD

**Issue by Costo** [GeoJSON-Net/GeoJSON.Net#63]
Hi,

`Feature` inherits the `Equals` implementation from `GeoJSONObject`. The `Equals` method returns `true` if both compared object have the property `BoundingBox` set to `null`.  

One problem I encountered because of this it that `collection.Features.IndexOf(myFeature)` will always return `0`, regardless of the actual index of the item in the list (given that all bboxes are `null`).

One workaround is to use `ReferenceEquals` instead: `collection.Features.FinIndex(x => object.ReferenceEquals(x, myFeature))`

Thanks for this lib!

**Comment by jbattermann** [comment]
Hi Vincent / @Costo,

thanks for reporting this & I think this is solved by #62 (pulling it in & publishing a new package shortly). I'll let you know when the updated package is up so you could have a look whether it solves your problem, too.

-J

**Comment by jbattermann** [comment]
@Costo the new version with adjusted .Equals and .GetHashCode implementations is up - would you mind checking whether this solves your issue as well?

**Comment by Costo** [comment]
It works now. Thank you.
