### ISSUE TITLE
Looping coördinates

### ISSUE THREAD

**Issue by nijs9** [GeoJSON-Net/GeoJSON.Net#72]
I'm deserializing a Json file with GeoJSON.net, which works fine in this way:

`var feature = JsonConvert.DeserializeObject<FeatureCollection>(text);`

But I can't find how to loop this deserialized 'thing' to get the coordinates (lat/lon) of each multilinestring...

Can someone help me?

Thanks!

**Comment by matt-lethargic** [comment]
Hi @nijs9 I'm one of the guys who's taken on this project so please bear with me. 
From my own experience I know that de-serialization is a little bit of a pain. Just quickly I did this

```
var featureCollection = JsonConvert.DeserializeObject<FeatureCollection>(json);
            
            foreach (var feature in featureCollection.Features)
            {
                if(!feature.Geometry.Type.Equals(GeoJSONObjectType.MultiLineString))
                    continue;

                var multilineString = feature.Geometry as MultiLineString;
                foreach (LineString lineString in multilineString.Coordinates)
                {
                    foreach (GeographicPosition lineStringCoordinate in lineString.Coordinates)
                    {
                        var lat = lineStringCoordinate.Latitude;
                        var lng = lineStringCoordinate.Longitude;
                    }
                }
            }
```

but it's not the best code and I don't like the casts in there. 

This is def something that we should look into a bit more
@hanssens Thoughts?

**Comment by nijs9** [comment]
Hi @matt-lethargic, thank you for your fast reply, I will test this code asap. Keep up the good work!

**Comment by matt-lethargic** [comment]
You should probably put so more checks in etc, but this should get you started.

**Comment by nijs9** [comment]
Hi @matt-lethargic, your code works, thanks. I'm trying to do the same thing for a GeoJson with Points, but this doesn't work:

`var features = JsonConvert.DeserializeObject<FeatureCollection>(text);

            List<Node> nodes = new List<Node>();

            foreach (Feature feature in features.Features)
            {
                if (!feature.Geometry.Type.Equals(GeoJSONObjectType.Point))
                    continue;

                 Point point = feature.Geometry as Point;

                //It's not possible to get point.Coordinates.Latitude


            }`

**Comment by matt-lethargic** [comment]
FYI Checkout the concrete-coords branch, I'm looking to have point.Coordinates as a GeographicPosition and not an IPosition. TBH I cannot see any reason why this couldn't be done and would make deserialization more streamlined.

**Comment by matt-lethargic** [comment]
I've just looked at this once again now that we have version 1.0 out. The problem ultimately is that a feature can have any type of geometry inside of it and the only was we can know what type it is would be to look at the Geometry.Type property, in which case the examples above would work.

Another thing I just thought of would be to create your own class that inherits from `Feature` something like this (I've not even built this code let alone tested it!!):

```
public class PointFeature : Feature
    {
        public PointFeature(IGeometryObject geometry, Dictionary<string, object> properties = null, string id = null) 
            : base(geometry, properties, id)
        {
        }

        public PointFeature(IGeometryObject geometry, object properties, string id = null) 
            : base(geometry, properties, id)
        {
        }

        public Point Point
        {
            get
            {
                return Geometry as Point;
            }
        }
    }
```

Also as of version 1.0.60-alpha you should be able to do
`point.Coordinates.Latitude` 
as I've sorted out the interfaces

Hope this helps, can I close this issue now?

**Comment by matt-lethargic** [comment]
ok scrap that.... I'm looking at a Feature<T> class, not sure why I didn't think of this!! Watch this space!
