### ISSUE TITLE
NuGet License points to 404 (.md missing)

### ISSUE THREAD

**Issue by percebus** [GeoJSON-Net/GeoJSON.Net#76]
[https://github.com/GeoJSON-Net/GeoJSON.Net/blob/master/LICENSE](https://github.com/GeoJSON-Net/GeoJSON.Net/blob/master/LICENSE)

Instead of

[https://github.com/GeoJSON-Net/GeoJSON.Net/blob/master/LICENSE.md](https://github.com/GeoJSON-Net/GeoJSON.Net/blob/master/LICENSE.md)

**Comment by matt-lethargic** [comment]
Looking into this now. Thanks for letting us know

**Comment by matt-lethargic** [comment]
Fixed, annoyingly had to release a new nuget version for it.

**Comment by matt-lethargic** [comment]
Fixed, annoyingly had to release a new nuget version for it.
