### ISSUE TITLE
GeographicPosition: order of longitude, latitude

### ISSUE THREAD

**Issue by alienlike** [GeoJSON-Net/GeoJSON.Net#77]
Why the decision to supply latitude and longitude to the `GeographicPosition` constructor in the opposite order of the GeoJSON spec? This makes it rather unintuitive, especially when using coordinates in anything other than 4326.

From https://tools.ietf.org/html/rfc7946#section-3.1.1:

"A position is an array of numbers.  There MUST be two or more elements.  _The first two elements are longitude and latitude, or easting and northing, precisely in that order_ and using decimal numbers. Altitude or elevation MAY be included as an optional third element."

Maybe this could be corrected in the new `Position` class?

**Comment by matt-lethargic** [comment]
Hi @alienlike ,

I've taken over from the original project owner and I understand what you're saying. For some reason people always say latitude before longitude, but in geo terms longitude should come first. 

The problem I'm stuck with is that it would obvisouly be bad practice for me to be changing the constructor param order in `GeographicPosition` and I'm struggling with the thought of changing the `Position` class as `GeographicPosition` inherits from it.

Another thing that would bother me about changing this would be that everyone who's going to upgrade to v1 (when I get it out there properly) will have to not only change `GeographicPosition` (as it's being deprecated) but then swap around the params in the constructor, if not their code will be totally wrong.

What I'm trying to say is that while I totally agree with you that longitude should come first, I don't feel that it would be right to go changing things this far down the line.

**Comment by alienlike** [comment]
@matt-lethargic: I totally understand where you're coming from. It's tough when so many people have adapted to the existing `GeographicPosition` interface.

I see that the new class would support a syntax like `new Position() { Longitude = lon, Latitude = lat }`, which should be sufficient.

**Comment by matt-lethargic** [comment]
You could also do

`new Position(longitude: lon, latitude: lat)`
