### ISSUE TITLE
The example throws a NotImplementedException

### ISSUE THREAD

**Issue by thulka** [GeoJSON-Net/GeoJSON.Net#8]
Provide a test case for the example at

https://en.wikipedia.org/wiki/GeoJSON

to demonstrate feature completeness.

**Comment by russcam** [comment]
@thulka @gzuri LineString serialization/deserialization is now implemented in v.0.1.38

**Comment by matt-lethargic** [comment]
Hi @thulka. Are you happy for this issue to be closed now?

**Comment by thulka** [comment]
excellent, thank you all !
