### ISSUE TITLE
Default CRS is removed during serialization

### ISSUE THREAD

**Issue by matt-lethargic** [GeoJSON-Net/GeoJSON.Net#89]
Just noticed that during serialization if a default CRS is specified it is removed. 
Looking through the spec https://tools.ietf.org/html/rfc7946#section-4 it doesn't mention removal of it, it just specifies the default.

Any comments welcome on this

**Comment by supermihi** [comment]
As far as I understand the spec, the CRS feature has been completely removed from the RFC, so it should be considered deprecated anyway?

Besides, I don't see a reason why to remove the default CRS from serialized JSON, but note that it is also *added* when deserializing JSON that does not have a `crs` attribute. Probably both "features" can safely be removed? Generally, I'd say that modifying `this` in `OnDeserialized` etc. is rather bad style anyway.

**Comment by supermihi** [comment]
In case you decide to remove the feature, here's a pull request that saves you some minutes. ;-) Apparently it's as easy as removing a few lines and modifying one unit test that explicitly tests for that behavior.
