### ISSUE TITLE
Geographic position removed but another project depends on it.

### ISSUE THREAD

**Issue by figuerres** [GeoJSON-Net/GeoJSON.Net#92]
[https://github.com/gksource/GeoJSON.Net.Contrib.EF](url)

depends on GeographicPosition   do function ....  can someone comment on the removal and how the other project should change to work with this change ??

what object replaces it ?   why was it removed ?

i just started to see if i can use this project , i have ef models that expose   the ef dbGeography type and the other project converts them to work with your code, or it used to...

**Comment by matt-lethargic** [comment]
Hi I can answer some of those questions.

What object replaces it? The [Position](https://github.com/GeoJSON-Net/GeoJSON.Net/blob/master/src/GeoJSON.Net/Geometry/Position.cs) class replaces it

Why was it removed? It was removed as ultimately it was only inheriting from the Position class anyway and it brings it inline with the [GeoJSON RFC](https://tools.ietf.org/html/rfc7946#section-3.1.1)

The Contrib.EF project is managed by @xfischer and I believe there has been a [commit to reflect this change](https://github.com/GeoJSON-Net/GeoJSON.Net.Contrib/commit/f5d701e08225310a0799133f3173496564e6fcf1)

Not wanting to palm you off, but as this is relating to the Contrib.EF project you should really post an issue there. And for me, I guess I should communicate with @xfischer better when it comes to breaking changes.

**Comment by figuerres** [comment]
@matt-lethargic , first thank you!  that was a fast reply!
in the contrib you linked to that was done, the one i linked to has not done that change , and it's  for EF support.  different project owner also.

I am grabbing the code to see if i can make a local copy that works in my project right now.
looks like the link i posted did not work 

https://github.com/gksource/GeoJSON.Net.Contrib.EF
created last year and no updates .....

**Comment by matt-lethargic** [comment]
I try and keep on issues even if I can't fix straight away.

Oh yes, didn't see that it wasn't part of our Contrib lib.

I couldn't tell you the full state of that project, but I've just downloaded the source, updated the GeoJSON.Net nuget package and rebuilt, it obviously failed, so then I just went through and changed each instance of GeographicPosition to Position and it built.

I couldn't tell you if it works or not, but that's where you could start

**Comment by figuerres** [comment]
yes thanks, just wanted to ping folks and see if anyone was aware and all that... i put an issue in the other project in case the author will update his code...

when i try my local copy i will know if the code works, if not i may have to use the other one, just that the EF one seemed like the right one at first look.

i know how to go from EF dbGeo to the SQL Clr version if i have to do that to bridge the gap.....

**Comment by matt-lethargic** [comment]
You could put a Pull Request in on the .EF project if you get it working, might help everyone.

Anyway thanks for letting us know even if we couldn't help. Are you happy for me to close this issue?

**Comment by figuerres** [comment]
yes i'll closwe it .
