### ISSUE TITLE
cannot check null feature

### ISSUE THREAD

**Issue by vishnu4** [GeoJSON-Net/GeoJSON.Net#94]
I had some code that just made sure that no one passed a null object as a feature, just something like:

```
private void DoSomethingWithFeature(GeoJSON.Net.Feature.Feature f)
{
     if (f !=null).....
}
```
Since the update from 1.0.62 to 1.1.63, this value errors out with a null exception every time, regardless if f is actually null or not.  Is there a different way i should be checking this parameter?

**Comment by matt-lethargic** [comment]
Hi @vishnu4 sorry that the update has caused you poroblems, I'll have a look shortly and get back to you

**Comment by matt-lethargic** [comment]
All sorted. Version 1.1.64 should now have a fix in place for this bug and sorry for any problems caused by this.

**Comment by vishnu4** [comment]
Passess my unit testing.  Thank you!
