### ISSUE TITLE
GeoJson Version 1.1.64 - Method not found - GeoJson.Net.Geometry.Polygon.get_Coordinates()

### ISSUE THREAD

**Issue by aadewojo** [GeoJSON-Net/GeoJSON.Net#96]
I formally used version 0.1.47 and it worked well for me when I try to get coordinates of a polygon, I have just updated to the above version, but gives an error when I try to access the coordinates of a polygon.

Additional information: Method not found: 'System.Collections.Generic.List`1<GeoJSON.Net.Geometry.LineString> GeoJSON.Net.Geometry.Polygon.get_Coordinates()'.

**Comment by matt-lethargic** [comment]
Hi @aadewojo , sorry you've had some issues when updating. 
There were some breaking changes between version 0.x and 1.x, I really wanted to publish them at the time, didn't have the time with other commitments.

Is there any chance you could post some of your code or something to show what you're doing so I can try and help a bit more. Polygon does still have a Coordinates property so not sure whats going on from the info you've posted.

**Comment by aadewojo** [comment]
Thank you so much for a prompt reply. Please find below the code I currently use.
`foreach (var curGeoJSON in geoJSONArr)
        {
            if (!string.IsNullOrEmpty(curGeoJSON))
            {
                var curFeature = JsonConvert.DeserializeObject<Feature>(curGeoJSON);
                BOSpatial curElement;
                if (curFeature.Geometry is GeoJSON.Net.Geometry.Polygon && ((GeoJSON.Net.Geometry.Polygon)curFeature.Geometry).Coordinates.Count > 0)
                {
                    curElement = new BOPolygon(long.Parse(curFeature.Properties["SpatialID"].ToString()), curFeature.Properties["name"].ToString(),
                        ((GeoJSON.Net.Geometry.Polygon)curFeature.Geometry).Coordinates[0]);
                }`
......
}
}

Class BOPolygon is as follows:
` public BOPolygon(long spatialID, string headerText, LineString points)
        {
            SpatialID = spatialID;
            HeaderText = headerText;
            PointsList = new List<Tuple<decimal, decimal>>();
            foreach (GeographicPosition x in points.Coordinates)
            {
              PointsList.Add(new Tuple<decimal, decimal>(decimal.Parse(x.Latitude.ToString()), decimal.Parse(x.Longitude.ToString())));
            }
}`

**Comment by aadewojo** [comment]
Hi,
Just to let you know I found a solution to this. I went through some of the closed issues and found something related to my question and I started digging out what could be the problem. I found out that a dll file for an older version of GeoJson was still in the dependencies folder, hence the reason for the error. So I deleted the dll file and rebuilt the application and it worked.

However I no more use Geographic position as this is no more in version 1.1.64.

Thank you.

**Comment by matt-lethargic** [comment]
Glad you found the problem. The GeographicPosition was removed in favour of the Position class, this brings thing more inline with the RFC. It should be more or less a straight swap.

**Comment by kennethhaspeel** [comment]
Sorry to drop in like this but i seem to be having the same problem. So I wasn't sure if I should open a new topic of comment in this one.
What outdated ddl file did you find? I'm getting the exact same error message with the following code i copied from the geojson-contrib page in a brand new console program where I installed the nuget packages. The version numbers seem up to date

```
using GeoJSON.Net.Geometry;
using Microsoft.SqlServer.Types;
using GeoJSON.Net.Contrib.MsSqlSpatial;

                var multiPolygon = new MultiPolygon(new List<Polygon>
                {
                    new Polygon(new List<LineString>
                    {
                        new LineString(new List<IPosition>
                        {
                            new Position(52.959676831105995, -2.6797102391514338),
                            new Position(52.9608756693609, -2.6769029474483279),
                            new Position(52.908449372833715, -2.6079763270327119),
                            new Position(52.891287242948195, -2.5815104708998668),
                            new Position(52.875476700983896, -2.5851645010668989),
                            new Position(52.882954723868622, -2.6050779098387191),
                            new Position(52.875255907042678, -2.6373482332006359),
                            new Position(52.878791122091066, -2.6932445076063951),
                            new Position(52.89564268523565, -2.6931334629377890),
                            new Position(52.930592009390175, -2.6548779332193022),
                            new Position(52.959676831105995, -2.6797102391514338)
                        })
                    }),
                    new Polygon(new List<LineString>
                    {
                        new LineString(new List<IPosition>
                        {
                            new Position(52.89610842810761, -2.69628632041613),
                            new Position(52.8894641454077, -2.75901233808515),
                            new Position(52.89938894657412, -2.7663172788742449),
                            new Position(52.90253773227807, -2.804554822840895),
                            new Position(52.929801009654575, -2.83848602260174),
                            new Position(52.94013913205788, -2.838979264607087),
                            new Position(52.937353122653533, -2.7978187468478741),
                            new Position(52.920394929466184, -2.772273870352612),
                            new Position(52.926572918779222, -2.6996509024137052),
                            new Position(52.89610842810761, -2.69628632041613)
                        })
                    })
                });
                SqlGeometry geo = multiPolygon.ToSqlGeometry();
```
gives the error 

> Method not found: System.Collections.Generic.List`1<GeoJSON.Net.Geometry.Polygon> GeoJSON.Net.Geometry.MultiPolygon.get_Coordinates().

**Comment by matt-lethargic** [comment]
This sounds like a Contrib library issue. I haven't heard anything from @xfischer for a while so could be an issue. The two libs are developed independently so might be an idea of logging this issue over there https://github.com/GeoJSON-Net/GeoJSON.Net.Contrib/issues feel free to keep this issue open though and if I get two mins I'll have a look.

**Comment by xfischer** [comment]
I’m still alive and I think you’re right. I’m going to check tomorrow.


Le 26 oct. 2017 à 16:03, Matt Lethargic <notifications@github.com<mailto:notifications@github.com>> a écrit :


This sounds like a Contrib library issue. I haven't heard anything from @xfischer<https://github.com/xfischer> for a while so could be an issue. The two libs are developed independently so might be an idea of logging this issue over there https://github.com/GeoJSON-Net/GeoJSON.Net.Contrib/issues feel free to keep this issue open though and if I get two mins I'll have a look.

**Comment by aadewojo** [comment]
Hi Kenneth,
I found GeoJson 0.0.48 or so. I can't remember the exact number but its from the version 0. I found the dll in the dependencies folder, so whenever I reference it in my solution, it uses this version instead of the installed version 1.1.64. And nugget didn't see that the old version was still installed, so I had to manually search till I found it.

Not sure if it is related to the issues you have though.

**Comment by kennethhaspeel** [comment]
i reported it here because the method that wasn't found, is from this project. Maybe the method changed name or something. But maybe i should have reported it in the Contrib project.
I noticed the build of Contrib failed

I have about 200 WFS services i have to get into sql. So this (and Contrib) could really save me a lot of hours :-)

Thanks for the really fast replies

@aadewojo : i installed the nuget package yesterday in a completly new project. So you're probably right. Not the same problem

**Comment by matt-lethargic** [comment]
I think this has something to do with the breaking changes going from version 0.x to 1.x classes were refactored and a few wee removed completely.

I've just build a console app from scratch and installed the 'GeoJSON.Net.Contrib.MsSqlSpatial' nuget package and I get the error

`System.DllNotFoundException: 'Unable to load DLL 'SqlServerSpatial110.dll': The specified module could not be found. `

@xfischer ...... any help?

**Comment by xfischer** [comment]
Hi, I have just released a new NuGet 0.3.1 from latest sources.
If you have any trouble with Sql Server Spatial, let me know. A simple NuGet restore should help.

**Comment by kennethhaspeel** [comment]
thanks to both @matt-lethargic and @xfischer for the very fast reponses. I'm going to test it tommorow and provide feedback

**Comment by kennethhaspeel** [comment]
Just ran my console app and no more get_coordinates error.
Now i'm getting another error. But not sure if it's an error in geojson.net, contrib or me just being stupid ;-)
Apparantly epsg 31370 is not recognized (The spatial reference identifier (SRID) is not valid. The specified SRID must match one of the supported SRIDs displayed in the sys.spatial_reference_systems catalog view).

But that's probably something i should ask on StackOverflow or something.

**Comment by xfischer** [comment]
@kennethhaspeel This is a common issue in Sql Server. StackOverflow should give you a workaround.
Mine is this : SQL Server SRID is informative, it does not affect geometry but rather indicates to a foreign eye "what is the SRID of this table".
You should use 0 as SRID with the following requirements :
- Make sure that when exposed, the SRID and CRS and properly set for consumers
- In order to perform spatial queries, you must use geometries with the same SRID (thus, 0) in WHERE predicates
I'm closing this as you problem with GeoJSON seems OK not.
Feel free to ask more if needed.
