### ISSUE TITLE
[Question] Why are Coordinates in LineString (and other classes) read-only?

### ISSUE THREAD

**Issue by cdrfun** [GeoJSON-Net/GeoJSON.Net#97]
Hi there,
first of all thanks for this great library.

I have a use case where I want to replace the coordinates of a LineString (because they were simplified using https://github.com/imshz/simplify-net). To do this i create a new LineString object and overwrite the existing one in the Coordinates object above. 
This doesn't work, because I don't have a setter. Is there a reason this was done the way it is? 

(To solve my issue I imported the GeoJSON.Net project and added setters.)

**Comment by xfischer** [comment]
If you add a setter, you should also check for bbox update.
Apart from this I don't see any issue.
What do you think @matt-lethargic and @hanssens ?

**Comment by matt-lethargic** [comment]
Hi, I've seen this, but not had chance to have a proper look and give a decent response. I'll have time later today to look and reply properly. 
Matt

**Comment by matt-lethargic** [comment]
The Coordinates property on line string was made read only when we were improving the and efficiency and speed. I don't see us changing it back. If you need to set new coordinates on a LineString you'll need to create a new instance of a LineString and pass them into the constructor

     var coordinates = new List<IPosition>
    {
        new Position(52.370725881211314, 4.889259338378906),
        new Position(52.3711451105601, 4.895267486572266),
        new Position(52.36931095278263, 4.892091751098633),
        new Position(52.370725881211314, 4.889259338378906)
    };

    var lineString = new LineString(coordinates);

**Comment by matt-lethargic** [comment]
@cdrfun  Can I close this issue? Feel free to say no if you want more help or discussion.

**Comment by cdrfun** [comment]
Thanks for your answer.

I didn't have any trouble creating a new, simplified LineString. But wasn't able to replace the existing one within the existing GeometryCollection. I wanted to keep the existing GeometryCollection, so I don't modify my original GeoJSON in any other way then simplification.

I understand that this may not be a usecase you want to cover, because the library would be slower. For me my workaround works ok, as I'm not modifying the bbox or anything. Feel free to close the issue ;)
